def employee(name="unknown",salary="unknown"):
    print("name",name)
    print("salary : ",salary)
employee()    
print("------------")
employee("nani",30000)
print("------------")
employee("ammulu",50000)
print("------------")
employee("shiva",75000)